### ISSUE TITLE
miss-match between setup.py and pypi page regarding supported python programming langues.

### ISSUE THREAD

**Issue by andrewkenny** [aeroxis/snek#1]
as described on pypi:

Programming Language :: Python
Programming Language :: Python :: 2
Programming Language :: Python :: 2.3
Programming Language :: Python :: 2.4
Programming Language :: Python :: 2.5
Programming Language :: Python :: 2.6
Programming Language :: Python :: 2.7
Programming Language :: Python :: 2 :: Only
Programming Language :: Unix Shell 

As described in setup.py:
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3.0",
        "Programming Language :: Python :: 3.1",
        "Programming Language :: Python :: 3.2",
        "Programming Language :: Python :: 3.3",
        "Programming Language :: Unix Shell",

Note, the inspiration behind this issue to mimimize / correct instances of "python 2 only" on pypi.
I am willing to submit a pull request in order to bring support to python 3.4 - 3.7 if necessary.

**Comment by davydany** [comment]
Andrew, you make a great point, but I am planning to not support Snek anymore. It seems like between cookiecutter and Pipfile, Snek seems to be re-inventing the wheel.
